services:
  - type: web
    name: anisheels
    runtime: static
    repo: https://github.com/Afatsiawu/Anisheels.git
    branch: main
    rootDir: project
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      # Render static SPA deep links
      # Important: include both exact and wildcard variants.
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html

      # Catch-all for any other client-side routes
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /
        destination: /index.html

